---
- name: Add Brightbox Ruby Apt Repository
  sudo: true
  apt_repository: repo='ppa:brightbox/ruby-ng' state=present

- name: Ensure Ruby is present
  sudo: true
  apt: pkg={{ item }} state=present
  with_items: ruby_versions

- name: Ensure bundler is present
  sudo: true
  gem: name=bundler state=present user_install=no
